- name: Configurações Debian12 servidor web
  hosts: debian12

  roles:
    - role: nginx
      vars:
        server_name: "meusite.com"
        document_root: "/var/www/meusite"

  tasks:
    - name: Define arquivo index.html
      ansible.builtin.copy:
        dest: /var/www/meusite/index.html
        content: |
          <H1> Meu Site! </H1>
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Reiniciar nginx
