- name: Instala pacotes
  hosts: win11

  tasks:
    - name: Install multiple packages sequentially
      chocolatey.chocolatey.win_chocolatey:
        name:
          - 7zip.install
          - firefox
          - notepadplusplus
      when: ansible_os_family == 'Windows'
      tags: packages
